name: compute module

on:
  push:
    paths:
      - "modules/compute/**"
  pull_request:
    paths:
      - "modules/compute/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS profile
        run: |
          mkdir -p ~/.aws
          cat <<EOF >> ~/.aws/credentials
          [terraform-practice]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          cat <<EOF >> ~/.aws/config
          [profile terraform-practice]
          region = us-east-1
          EOF

      - name: Terraform fmt check
        run: terraform fmt -check -recursive modules/compute

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -target=module.compute
